/**
 * Copyright 2014 aixigo AG
 * Released under the MIT license.
 * http://laxarjs.org/license
 */
define( [], function() {
   'use strict';

   var generatedMessages = [];
   var messageGenerator = jasmine.createSpy( 'messageGenerator' ).andCallFake( function() {
      return generatedMessages;
   } );
   var messageGeneratorFactory = jasmine.createSpy( 'messageGeneratorFactory' ).andReturn( messageGenerator );

   // make the generator itself accessible from within tests
   messageGeneratorFactory.messageGenerator = messageGenerator;

   // allow setting of fake messages generated by jjve
   messageGeneratorFactory.setGeneratedMessages = function( messages ) {
      generatedMessages = Array.isArray( messages ) ? messages : [];
   };

   return messageGeneratorFactory;
} );
